[build]
  command = "npm ci && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers de sécurité et performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirections
[[redirects]]
  from = "/api/*"
  to = "https://api.chantipro.fr/:splat"
  status = 200
  force = true

# Configuration par branche
[context.production]
  command = "npm ci && npm run build"
  environment = { NODE_ENV = "production", NEXT_PUBLIC_ENVIRONMENT = "production", NPM_FLAGS = "--production=false" }

[context.develop]
  command = "npm ci && npm run build"
  environment = { NODE_ENV = "production", NEXT_PUBLIC_ENVIRONMENT = "preprod", NPM_FLAGS = "--production=false" }

[context.deploy-preview]
  command = "npm ci && npm run build"
  environment = { NODE_ENV = "production", NEXT_PUBLIC_ENVIRONMENT = "preview", NPM_FLAGS = "--production=false" }