name: CI/CD Pipeline ChantirPro

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Clean install dependencies
      run: |
        echo "🧹 Cleaning node_modules and package-lock.json..."
        rm -rf node_modules package-lock.json
        echo "📦 Running fresh npm install..."
        npm install
    
    - name: Check TypeScript errors
      run: |
        echo "🔍 Checking for TypeScript errors..."
        npx tsc --noEmit || true
    
    - name: Build Next.js site
      run: |
        echo "🏗️ Building Next.js site..."
        npm run build
      env:
        NEXT_TELEMETRY_DISABLED: 1
    
    - name: Export static site
      run: |
        echo "📤 Exporting static site..."
        npx next export || echo "Export might be automatic with Next.js 13+"
    
    - name: Check build output
      run: |
        echo "📁 Checking build directories..."
        if [ -d "out" ]; then
          echo "✅ out directory found"
          echo "Contents of out directory:"
          ls -la out/
        else
          echo "❌ out directory NOT found"
          echo "Looking for .next directory..."
          if [ -d ".next" ]; then
            echo "✅ .next directory found"
          fi
        fi

    # Deploy to Preprod (develop branch)
    - name: Deploy to Netlify Preprod
      if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
      uses: nwtgck/actions-netlify@v2.0
      with:
        publish-dir: './out'
        production-deploy: false
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions - Preprod - ${{ github.sha }}"
        enable-pull-request-comment: false
        enable-commit-comment: false
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1

    # Deploy to Production (main branch)
    - name: Deploy to Netlify Production
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: nwtgck/actions-netlify@v2.0
      with:
        publish-dir: './out'
        production-deploy: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions - Production - ${{ github.sha }}"
        enable-pull-request-comment: false
        enable-commit-comment: false
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1